version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=finance
      - POSTGRES_USER=finance
      - POSTGRES_PASSWORD=finance
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./ops/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
  app:
    build:
      context: .
    image: finance-forecast-app:prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finance
      - SPRING_DATASOURCE_USERNAME=finance
      - SPRING_DATASOURCE_PASSWORD=finance
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
  pg_exporter:
    image: bitnami/postgres-exporter:0.15.0
    environment:
      - DATA_SOURCE_NAME=postgresql://finance:finance@db:5432/finance?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9187:9187"

volumes:
  db-data:

