services:
  db:
    image: postgres:16
    secrets:
      - pg_user
      - pg_password
    environment:
      - POSTGRES_DB=finance
      - POSTGRES_USER_FILE=/run/secrets/pg_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./ops/postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10
  app:
    build:
      context: .
    image: finance-forecast-app:prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms512m -Xmx1024m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/finance?sslmode=${DB_SSLMODE:-disable}
      - SPRING_DATASOURCE_USERNAME_FILE=/run/secrets/pg_user
      - SPRING_DATASOURCE_PASSWORD_FILE=/run/secrets/pg_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SERVER_SHUTDOWN=graceful
      - SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE=30s
    secrets:
      - pg_user
      - pg_password
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 512M
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 5
  pg_exporter:
    image: bitnami/postgres-exporter:0.15.0
    environment:
      - DATA_SOURCE_NAME=postgresql://finance:finance@db:5432/finance?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "9187:9187"

volumes:
  db-data:

secrets:
  pg_user:
    file: ./ops/secrets/pg_user.txt
  pg_password:
    file: ./ops/secrets/pg_password.txt

